COMPONENT=CMCServerExC
# uncomment this for network programming support
# BOOTLOADER=tosboot


PFLAGS += -DNEW_PRINTF_SEMANTICS -DPRINTFUART_ENABLED
#PFLAGS += -DNEW_PRINTF_SEMANTICS

# Enable debug output
PFLAGS += -DDEBUG_OUT

# Include the CMC folder
CFLAGS += -I../../CMC

include $(MAKERULES)

